global with sharing class OpportunityOffer {
	
	global String offerID {get; set;}
	global Decimal amount {get; set;}	
	global Decimal dailyCollection {get; set;}		
	global Decimal duration {get; set;}		
	global String productName {get; set;}	
	global Decimal purchase {get; set;}		
	global Decimal dailyPayment {get; set;}		
	global Decimal numOfPayments {get; set;}	
	global String externalID {get; set;}		
	global String source {get; set;}	
    global String notes {get; set;}	
    global Decimal LOC_Fee {get; set;}	
    global Decimal LOC_Limit {get; set;}	
    global Decimal LOC_Drawterm {get; set;}	
    global Decimal LOC_totalterm {get; set;}	
	
}